global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1h
  receiver: 'email'

receivers:
- name: 'email'
  email_configs:
  - to: 'ecommercewebsiteofhoang@gmail.com'
    from: 'hochiminhoffline1001@gmail.com'
    smarthost: 'smtp.gmail.com:587'
    auth_username: 'hochiminhoffline1001@gmail.com'
    auth_identity: 'hochiminhoffline1001@gmail.com'
    auth_password: 'kgrt agwr obog llhe'
    send_resolved: true
    require_tls: true
    headers:
      From: 'Alertmanager <hochiminhoffline1001@gmail.com>'
      Subject: '{{ template "email.subject" . }}'
