version: "3.8"

services:
  accounts:
    image: dobahoang/accounts:latest
    ports:
      - "8080:8080"
    networks:
      - dobahoang

  
  loans:
    image: dobahoang/loans:latest
    ports:
      - "8090:8090"
    networks:
      - dobahoang
    
  cards:
    image: dobahoang/cards:latest
    ports:
      - "9000:9000"
    networks:
      - dobahoang

  
  gatewayserver:
    image: dobahoang/gatewayserver:latest
    mem_limit: 700m
    ports:
      - "8072:8072"
    networks:
      - dobahoang
    depends_on:
      - configserver
      - eurekaserver
      - cards
      - loans
      - accounts
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 180s
    environment:
      SPRING_APPLICATION_NAME: gatewayserver
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      # SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
    
networks:
  dobahoang: