global:
  scrape_interval:     15s
  evaluation_interval: 15s


  external_labels:
      monitor: 'docker-host-alpha'

# Load and evaluate rules in this files every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"
  - "first.rules"
  - "app.rules"
  - "linux.rules"
  - "windows.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'nodeexporter_1'
    scrape_interval: 5s
    static_configs:
      - targets: ['54.151.191.165:8080']

  - job_name: 'nodeexporter_2'
    scrape_interval: 5s
    static_configs:
      - targets: ['54.151.191.165:8081']

  - job_name: 'nodeexporter_3'
    scrape_interval: 5s
    static_configs:
      - targets: ['54.151.191.165:8082']

  - job_name: 'win-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: [ '18.141.186.162:9182']


  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

  # - job_name: 'accounts'
  #   metrics_path: '/actuator/prometheus'
  #   static_configs:
  #     - targets: [ 'accounts:8080' ]
  # - job_name: 'loans'
  #   metrics_path: '/actuator/prometheus'
  #   static_configs:
  #     - targets: [ 'loans:8090' ]
  # - job_name: 'cards'
  #   metrics_path: '/actuator/prometheus'
  #   static_configs:
  #     - targets: [ 'cards:9000' ]

  - job_name: 'microservices-app'
    file_sd_configs:
      - files:
        - 'targets_all.json'  # Update this path
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.+):.*'
        target_label: instance
        replacement: '${1}'

  - job_name: 'blackbox'
    scrape_interval: 10s
    metrics_path: /probe
    static_configs:
      - targets:
          - https://google.com
          - https://viblo.asia
          - https://viblo.asia/api/web-init-404
    params:
      module: [ http_2xx ]
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: "blackbox_exporter:9115"

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'alertmanager:9093'


