version: "3.8"

services:

  accounts:
    image: dobahoang/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - dobahoang-network
    
  loans:
    image: dobahoang/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - dobahoang-network
    
  cards:
    image: dobahoang/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - dobahoang-network
    
networks:
  dobahoang-network: